In [1]:
from typing import List, Tuple, Callable

In [2]:
def chech_shape(*args):
    assert args, "Tanımlı vectör bulunumadı"
    num_element = len(args[0])
    for v in args:
        assert num_element == len(v), "vektörler aynı boyutta olmalı"

chech_shape([0],[2])

## Vectors

In [3]:
Vector = List[float]

In [4]:
a = [20,0,12]
[[1,2],[1,3]]
[[[1,2,2]]]

In [5]:
txt = ["abcde"]
txt = ["a","b","c","d"]
txt_id = [0,1,2,3]
txt_one_hot = [[0,0],[0,1],[1,0],[1,1]]

In [6]:
def add(v: Vector, w: Vector) -> Vector:
    assert len(v) == len(w), "vektörler aynı boyutta olmalı"

    return [v_i + w_i for v_i, w_i in zip(v, w)]

In [7]:
def vectors_sum(*args: List[Vector]):
   chech_shape(*args)
   num_elements = len(args[0])
   # assert all(len(v) == num_elements for v in args), "Vektörlerin aynı boyutta olmalı"
   return  [sum(vector[i] for vector in args)
            for i in range(num_elements)]
vectors_sum([1,5],[5,5])

[6, 10]

In [8]:
def scalar_multiply(c: float, v: Vector):
    return [c * v_i for v_i in v]
scalar_multiply(2, [1, 2, 3])

[2, 4, 6]

In [9]:
def vector_mean(*args: List[Vector]) -> Vector:
    n = len(args)
    return scalar_multiply(1/n, vectors_sum(*args))
vector_mean([1,2], [3, 4], [5, 6])

[3.0, 4.0]


![The San Juan Mountains are beautiful!](https://media5.datahacker.rs/2020/04/Picture27-1024x386.jpg "San Juan Mountains")
![The San Juan Mountains are beautiful!](https://miro.medium.com/max/835/1*mEmVBrqcHd1MQux6SnptGQ.png "San Juan Mountains")



In [9]:
def dot(v: Vector, w: Vector) -> float:
    chech_shape(v,w)
    return sum(v_i * w_i for v_i, w_i in zip(v, w))

dot([1,2,3],[1,2,3])

14

## Matrixs

In [12]:
Matrix = List[Vector]

In [10]:
A = [[1, 2, 3], 
     [4, 5, 6]]

B = [[1, 2],  
     [3, 4],
     [5, 6]]

![The San Juan Mountains are beautiful!](https://miro.medium.com/max/1400/1*YGcMQSr0ge_DGn96WnEkZw.png "San Juan Mountains")

In [13]:
def get_col(A: Matrix, i: int):
    return [a[i] for a in A]
def get_row(A: Matrix, i: int):
    return A[i]
def get_shape(A: Matrix):
    return len(A), len(A[0])
def make_matrix(row: int, col:int , fill=0):
    return [
        [fill for j in range(col)] for i in range(row)
    ]
def matmut(A: Matrix, B:Matrix):
    r = get_shape(A)[0]
    c = get_shape(B)[1]
    assert  r == c, "Matrislerin satır ve sütün uyumlu olmalıdır"
    result = make_matrix(r,c)
    for row in range(len(A)):
        for col in range(len(B[0])):
            tmp = dot(get_row(A,row), get_col(B, col))
            # print(row, col,tmp)
            result[row][col] = tmp
    return result

In [16]:
get_shape(A), get_shape(B)

((2, 3), (3, 2))

In [14]:
matmut(A, B)

[[22, 28], [49, 64]]

In [17]:
# Transpose 
def transpose(matrix):
    return [[matrix[j][i] for j in range(len(matrix))] for i in range(len(matrix[0]))]


In [16]:
list(zip(*B))

[(1, 3, 5), (2, 4, 6)]

In [17]:
A = [[1, 2, 3],
	[4, 5, 6]]
B = [[10,11],[20,21],[30,31]]

In [18]:
get_row(A,0), get_col(B,0)

([1, 2, 3], [10, 20, 30])

In [19]:
dot(get_row(A,0),get_col(B,0))

140

In [20]:
a = make_matrix(2,2,0)
get_shape(a)

(2, 2)

In [21]:
matmut(A, B)

[[140, 146], [320, 335]]

In [22]:
#            user 0  1  2  3  4  5  6  7  8  9
#
friend_matrix = [[0, 1, 1, 0, 0, 0, 0, 0, 0, 0],  # user 0
                 [1, 0, 1, 1, 0, 0, 0, 0, 0, 0],  # user 1
                 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],  # user 2
                 [0, 1, 1, 0, 1, 0, 0, 0, 0, 0],  # user 3
                 [0, 0, 0, 1, 0, 1, 0, 0, 0, 0],  # user 4
                 [0, 0, 0, 0, 1, 0, 1, 1, 0, 0],  # user 5
                 [0, 0, 0, 0, 0, 1, 0, 0, 1, 0],  # user 6
                 [0, 0, 0, 0, 0, 1, 0, 0, 1, 0],  # user 7
                 [0, 0, 0, 0, 0, 0, 1, 1, 0, 1],  # user 8
                 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0]]  # user 9

In [23]:
import numpy as np

# Broadcasting

aa = np.array([
[0.8, 2.9, 3.9],
[52.4, 23.6, 36.5],
[55.2, 31.7, 23.9],
[14.4, 11, 4.9]
])
 
a = np.array([5, 7, 3])
b = np.array([90, 50, 0])
 
c = aa * b
print (c)

[[  72.  145.    0.]
 [4716. 1180.    0.]
 [4968. 1585.    0.]
 [1296.  550.    0.]]


In [24]:
macros = np.array([
[0.8, 2.9, 3.9],
[52.4, 23.6, 36.5],
[55.2, 31.7, 23.9],
[14.4, 11, 4.9]
])

result = np.zeros_like(macros)

cal_per_macro = np.array([3, 3, 8])

for i in range(macros.shape[0]):
	result[i, :] = macros[i, :] * cal_per_macro

result


array([[  2.4,   8.7,  31.2],
       [157.2,  70.8, 292. ],
       [165.6,  95.1, 191.2],
       [ 43.2,  33. ,  39.2]])

In [25]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]])
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [26]:
a.shape, b.shape

((2, 2), (2, 2))

In [27]:
b = np.array([[11,12,1],[13,14,1]])
np.matmul(a,b)

array([[37, 40,  3],
       [85, 92,  7]])

## Numpy

https://colab.research.google.com/github/cs231n/cs231n.github.io/blob/master/python-colab.ipynb#scrollTo=VzrEo4KGL9jP&uniqifier=1

### Generate a matrix

In [19]:
import numpy as np

In [20]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)                  

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [21]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [24]:
a = np.zeros((5,6))  # Create an array of all zeros
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [27]:
b = np.ones((1,2,3))   # Create an array of all ones
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]]


In [33]:
c = np.full((2,5,5), 5) # Create a constant array
print(c)

[[[5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]]

 [[5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]]]


In [35]:
d = np.eye(5)        # Create a 2x2 identity matrix
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [37]:
e = np.random.random((5,2)) # Create an array filled with random values
print(e)

[[0.29003839 0.14690055]
 [0.85683254 0.28335527]
 [0.82165716 0.13481991]
 [0.73746536 0.10987137]
 [0.91632687 0.81404379]]


In [44]:
# Linear 
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

### Array indexing

In [59]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
print(a)
b = a[:2, 1:3]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [60]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

2
77


In [61]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [62]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [63]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


In [66]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [68]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [84]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[1, 2], [1, 1]])

# # Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[4 6]
[2 2]


In [88]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [95]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[[1,0,2,3], b])  # Prints "[ 1  6  7 11]"

[ 4  3  7 11]


In [96]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [106]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [122]:
a[(a<5)]

array([1, 2, 3, 4])

In [107]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
# print(a[a > 2])

[3 4 5 6]


### Array math

In [125]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [126]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [127]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [128]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [129]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


 We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [130]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


In [134]:
print(v @ w)

219


In [135]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[29 67]
[29 67]
[29 67]


In [153]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"
print(np.sum(x, axis=-1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]
[3 7]


In [154]:
# x = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
# x.shape

In [157]:
print(x)
print("transpose\n", x.T)

[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]


### Broadcasting

In [158]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [159]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [51]:
y = x + vv  # Add x and vv elementwise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [165]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [164]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [177]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

[[2 2 4]
 [5 5 7]]


In [71]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [186]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [190]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [191]:
np.reshape(v, (3, 1))

array([[1],
       [0],
       [1]])

### Array Manipulation

In [192]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

In [193]:
x.shape, x

((4, 3),
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]))

In [195]:
x.reshape((2,2,3))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [196]:
# Flatten
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [198]:
# Transpose
x.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [206]:
#expand_dimension
print(x.shape)
print(x)
x_e = np.expand_dims(x,2)
x_e.shape, x_e

(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


((4, 3, 1),
 array([[[ 1],
         [ 2],
         [ 3]],
 
        [[ 4],
         [ 5],
         [ 6]],
 
        [[ 7],
         [ 8],
         [ 9]],
 
        [[10],
         [11],
         [12]]]))

In [207]:
# Sequeeze
np.squeeze(x_e,2)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [215]:
# Concantenate
a = [[1,2,3]]
b = [[4,5,6]]
np.concatenate([a,b],1)

array([[1, 2, 3, 4, 5, 6]])

In [216]:
# Stack
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a.shape, b.shape)

(2, 2) (2, 2)


In [217]:
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [224]:
x = np.stack((a,b), 0)
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [221]:
y = np.stack((a,b), 1)
y.shape

(2, 2, 2)

In [225]:
a.shape, b.shape

((2, 2), (2, 2))

In [226]:
np.vstack((a,b))

(4, 2)

In [229]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Arithmetic Operations

In [ ]:
np.add(a,b) 
np.subtract(a,b) 
np.multiply(a,b)
np.divide(a,b)

### Argmax , argmin 

In [230]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]])

In [233]:
a

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [236]:
np.argmax(a, 0) 

array([1, 2, 0])

In [179]:
np.argmin(a)

5

### np.where

In [241]:
x.shape

(2, 2, 2)

In [237]:
idx = np.where(x > 3) 

In [242]:
idx

(array([0, 1, 1, 1, 1]), array([1, 0, 0, 1, 1]), array([1, 0, 1, 0, 1]))

In [243]:
x[idx]

array([4, 5, 6, 7, 8])

### Linear Algebra

In [251]:
a = np.array([[1,2],[3,4],[5,6]]) 
b = np.array([[11,12],[13,14],[13,14]]) 
# [[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]
print(a.shape, b.shape, b.T.shape)
np.dot(a,b.T)

(3, 2) (3, 2) (2, 3)


array([[ 35,  41,  41],
       [ 81,  95,  95],
       [127, 149, 149]])

In [254]:
a = [[1,0],[0,1],[0,1]] 
b = [[4,1],[2,2]] 
np.matmul(a,b)

[[4 1]
 [2 2]
 [2 2]]


array([[4, 1],
       [2, 2],
       [2, 2]])